Repository projectceladon/device-androidia-mixins, pull requests merged in 2022-11, with the labels that each got.

#1509 Enable kernel configs for Android platform hardening
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1511 Remove libmd.so from additional native libraries
  groups/public-libraries/true/public.libraries.txt
Labels: PR approved, Valid commit message

#1515 Remove libmd.so from additional native libraries
  groups/public-libraries/true/public.libraries.txt
Labels: PR approved

#1513 Gptimage will not be built by command "make flashfiles publish_ci"
  groups/gptbuild/true/BoardConfig.mk
Labels: PR approved, Valid commit message

#1516 Rename the license file to avoid confusion
  LICENSE
  groups/device-specific/caas/product.mk
  groups/device-specific/caas_cfc/product.mk
  groups/device-specific/caas_dev/product.mk
  groups/device-specific/celadon_ivi/product.mk
  groups/device-specific/celadon_tablet/product.mk
Labels: PR approved, Valid commit message

#1505 Fix selinux error of mediatranscoding.
  groups/media/auto/BoardConfig.mk
Labels: PR approved

#1519 Enable Identity Credential HAL
  groups/device-specific/caas/framework_manifest.xml
  groups/device-specific/caas/manifest.xml
  groups/device-specific/caas/product.mk
Labels: PR approved, Valid commit message

#1521 resolving defconfig conflicts for kernel 5.15.74 rebase
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1522 adding cam sharing script
  groups/device-specific/caas/BoardConfig.mk
  groups/device-specific/caas/files.spec
  groups/device-specific/caas/product.mk
Labels: Valid commit message

#1514 Update init.rc file for audio module loading
  groups/audio/project-celadon/init.rc
  groups/device-specific/caas/sof_audio/configure_sof.sh
Labels: PR approved, Valid commit message

#1510 Update kernel configs for hda and sof selection using android property
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1524 Add A2DP source role support in Android T
  groups/audio/project-celadon/default/policy/a2dp_in_audio_policy_configuration_7_0.xml
  groups/audio/project-celadon/default/policy/audio_policy_configuration.xml
  groups/audio/project-celadon/default/policy/bluetooth_audio_policy_configuration_7_0.xml
  groups/audio/project-celadon/product.mk
  groups/bluetooth/btusb/product.mk
  groups/device-specific/caas/manifest.xml
Labels: PR approved, Valid commit message

#1525 re-enabling drm_i915_memtrack flag
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1533 Enforce the debugfs restriction
  groups/device-specific/caas/caas.mk
Labels: PR approved, Valid commit message

#1534 Migrate Bluetooth Audio HAL to AIDL
  groups/bluetooth/btusb/product.mk
  groups/device-specific/caas/manifest.xml
Labels: PR approved, Valid commit message

#1527 Use sysfs to replace debugfs in initrc for virtio2d/3d distinction
  groups/graphics/auto/auto_hal.in
Labels: PR approved, Valid commit message

#1528 Clipboard
  groups/device-specific/caas/BoardConfig.mk
  groups/device-specific/caas/product.mk
Labels: Valid commit message

#1538 disable intel_lmce which not supported by virtual machines
  groups/kernel/BoardConfig.mk
Labels: PR approved, Valid commit message

#1539 disable intel_lmce which not supported by virtual machines
  groups/kernel/BoardConfig.mk
Labels: PR approved, Valid commit message

#1536 add rpc-services group
  groups/rpc-services/default
  groups/rpc-services/doc.spec
  groups/rpc-services/false/empty_dir
  groups/rpc-services/grpc/AndroidBoard.mk
  groups/rpc-services/grpc/BoardConfig.mk
  groups/rpc-services/grpc/auto_hal.in
  groups/rpc-services/grpc/files.spec
  groups/rpc-services/grpc/init.rc
  groups/rpc-services/grpc/option.spec
  groups/rpc-services/grpc/product.mk
  groups/rpc-services/mixinfo.spec
Labels: PR approved, Valid commit message

#1544 Add support for linux-intel-lts2021 kernel
  groups/kernel/AndroidBoard.mk
  groups/kernel/BoardConfig.mk
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/caas_diffconfig
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/debug_diffconfig
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
  groups/kernel/option.spec-gmin
Labels: PR approved, Valid commit message

#1545 Modifying the path since we removed caas_dev
  groups/device-specific/caas/addon/debian/control
Labels: PR approved, Valid commit message

#1548 Refine the fastboot format command for installer
  groups/flashfiles/ini/flashfiles.ini
Labels: PR approved, Valid commit message

#1547 Fix android not booting in sriov mode
  groups/graphics/auto/BoardConfig.mk
Labels: PR approved, Valid commit message

#1549 Enable Control Flow Integrity and zero-init everything on stack configs
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved, Valid commit message
