Repository projectceladon/device-androidia-mixins, pull requests merged in 2022-06, with the labels that each got.

#1397 Added Github actions for the project
  .github/workflows/Runchecks.yaml
Labels: Linting passed, Invalid commit message

#1400 Use adl as default C2 performance setting
  groups/codec2/true/files.spec
  groups/codec2/true/product.mk
  groups/codecs/configurable/auto_hal.in
Labels: PR approved

#1403 virtual node binaries
  groups/device-specific/caas/BoardConfig.mk
  groups/device-specific/caas/cam_sharing/0001-Netlink-sync.patch
  groups/device-specific/caas/cam_sharing/IntelCameraService
  groups/device-specific/caas/cam_sharing/virtualcamera.service
  groups/device-specific/caas/files.spec
  groups/device-specific/caas/product.mk
Labels: Invalid commit message, PR approved

#1407 Resolve issue of usb card listing as sdcard
  groups/storage/sdcard-v-usb-only/fstab
  groups/storage/sdcard-v-usb-only/fstab.recovery
  groups/storage/sdcard-v-usb-only/init.rc
  groups/storage/sdcard-v-usb-only/product.mk
Labels: PR approved, Valid commit message

#1408 Added PR Label input for github workflow
  .github/workflows/Runchecks.yaml
Labels: Invalid commit message

#1404 ADD values_model for ADL-S board
  groups/codecs/configurable/auto_hal.in
Labels: PR approved, Valid commit message
