Repository projectceladon/device-androidia-mixins, pull requests merged in 2022-09, with the labels that each got.

#1453 Fix ivi software cannot boot up on ADL platform
  groups/device-specific/celadon_ivi/overlay/packages/Car/service/res/values/config.xml
Labels: Valid commit message

#1448 upgrading sensors@1.0-service to sensors@2.0-service
  groups/device-specific/caas/framework_manifest.xml
  groups/device-specific/caas/manifest.xml
  groups/sensors/mediation/BoardConfig.mk
  groups/sensors/mediation/option.spec
  groups/sensors/mediation/product.mk
Labels: Valid commit message

#1456 Kernel: Guest config for v5.15.44
  groups/kernel/gmin64/config-lts/lts2021-chromium/caas_diffconfig
  groups/kernel/gmin64/config-lts/lts2021-chromium/debug_diffconfig
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1462 Fix blackscreen issue
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1464 group:mixin:caas: Update QEMU version from 6.0.0 to 7.0.0
  groups/device-specific/caas/guest_pm_control
  groups/device-specific/caas/wakeup.py
Labels: PR approved, Valid commit message

#1466 Add vm-manager.deb to release tar ball
  groups/device-specific/caas/BoardConfig.mk
  groups/device-specific/caas/files.spec
  groups/device-specific/caas/product.mk
Labels: Valid commit message

#1470 CtsOsTestCases ro.vndk.version should be comared with Build.VERSION_C…
  groups/boot-arch/project-celadon/BoardConfig.mk
  groups/boot-arch/project-celadon/files.spec
  groups/boot-arch/project-celadon/product.mk
  groups/boot-arch/project-celadon/set_soc_prop.sh
  groups/device-specific/caas/caas.mk
  groups/device-specific/caas/init.rc
Labels: Valid commit message

#1480 Move the config file for Car to correct path in overlay
  groups/device-specific/celadon_ivi/overlay/packages/services/Car/service/res/values/config.xml
Labels: Valid commit message

#1481 guest_pm_control: Remove hardcoding of sendkey binary call
  groups/device-specific/caas/guest_pm_control
Labels: PR approved, Valid commit message

#1485 Enabling Atrace HAL in framework_manifest.
  groups/device-specific/caas/framework_manifest.xml
Labels: PR approved

#1484 Gptimage will not be built by command "make flashfiles publish_ci"
  groups/gptbuild/true/BoardConfig.mk
Labels: PR approved, Valid commit message

#1486 Fix CtsDeqpTestCases dEQP-VK failure
  groups/graphics/auto/auto_hal.in
Labels: Valid commit message

#1475 Configure rro overlay for connectivity to fix CTS issue
  groups/wlan/iwlwifi/product.mk
Labels: PR approved

#1482 Addition of atrace in framework manifest file
  groups/device-specific/caas/framework_manifest.xml
Labels: Invalid commit message, PR approved
