Repository projectceladon/device-androidia-mixins, pull requests merged in 2023-08, with the labels that each got.

#1651 [celadon_ivi] enable HWP and intel_pstate active mode
  groups/kernel/BoardConfig.mk
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: Valid commit message

#1710 Support av1 8k decoding
  groups/codec2/true/media_codecs_intel_c2_video.xml
Labels: Valid commit message

#1718 Userdata checkpoint enable
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved

#1714 USB device mode changes for IVI
  groups/usb-gadget/auto/auto_hal.in
  groups/usb-init/true/load_usb_modules.in
Labels: PR approved, Valid commit message, Developer Approved

#1720 adding needed permission for fan
  groups/thermal/thermal-daemon/init.rc
Labels: PR approved, Valid commit message

#1719 Support userspace fastboot over USB
  groups/device-specific/celadon_ivi/BoardConfig.mk
Labels: PR approved, Valid commit message

#1725 Add inlinecrypt mount option for data partition
  groups/boot-arch/project-celadon/fstab
Labels: PR approved, Valid commit message
