Repository projectceladon/device-androidia-mixins, pull requests merged in 2023-05, with the labels that each got.

#1628 Add Evs pipeline services
  groups/device-type/car/product.mk
Labels: PR approved, Valid commit message

#1626 Load audio modules
  groups/audio/project-celadon/init.rc
  groups/audio/project-celadon/option.spec
Labels: PR approved, Valid commit message

#1629 kernel: move debug configs from x86_64_defconfig to debug_diffconfig
  groups/kernel/gmin64/config-lts/lts2021-chromium/debug_diffconfig
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message

#1635 Enable acrn guest, virtio-gpio and virtio-i2c
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/caas_diffconfig
Labels: PR approved, Valid commit message

#1640 linux-intel-lts2021: kernel config update for 5.15.106
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved, Valid commit message

#1644 Add kernel command line parameter to enable ramoops
  groups/kernel/BoardConfig.mk
Labels: PR approved, Valid commit message

#1641 Allow inclusion of super.img into out/dist based on build flag
  groups/boot-arch/project-celadon/BoardConfig.mk
Labels: PR approved, Valid commit message

#1646 Delete Runchecks.yaml
  .github/workflows/Runchecks.yaml
Labels: Invalid commit message

#1648 [celadon_ivi] Add kernel command line parameter to enable ramoops
  groups/device-specific/celadon_ivi/BoardConfig.mk
  groups/kernel/BoardConfig.mk
Labels: PR approved, Valid commit message

#1643 linux-intel-lts2021: enable intel_idle
  groups/device-specific/celadon_ivi/BoardConfig.mk
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: Invalid commit message, PR approved

#1650 Configure rro overlay for overriding captive_portal_http_url
  groups/net/common/product.mk
Labels: PR approved, Valid commit message

#1642 Allow inclusion of super.img into out/dist based on build flag
  groups/boot-arch/project-celadon/BoardConfig.mk
Labels: Valid commit message
