Repository projectceladon/device-androidia-mixins, pull requests merged in 2023-09, with the labels that each got.

#1734 Revert "adding needed permission for fan"
  groups/thermal/thermal-daemon/init.rc
Labels: PR approved, Valid commit message

#1735 Set cameraIdOffset to 0 for uvc device
  groups/camera-ext/ext-camera-only/external_camera_config.xml
  groups/camera-ext/ivi/external_camera_config.xml
Labels: PR approved

#1733 Add support for stmmac controller
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
  groups/net/common/init.rc
  groups/net/common/option.spec
Labels: Valid commit message

#1727 Enable optee in mixins
  groups/optee/default
  groups/optee/doc.spec
  groups/optee/false/empty_dir
  groups/optee/mixinfo.spec
  groups/optee/true/AndroidBoard.mk
  groups/optee/true/BoardConfig.mk
  groups/optee/true/fstab
  groups/optee/true/fstab.recovery
  groups/optee/true/init.rc
  groups/optee/true/product.mk
Labels: PR approved, Valid commit message, Developer Approved

#1741 Ignore .git when running mixins
  mixin-update
Labels: PR approved, Valid commit message

#1732 Enable optee driver config in mixins
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved, Valid commit message

#1737 Add ACRN hypervisor support
  groups/boot-arch/project-celadon/AndroidBoard.mk
  groups/boot-arch/project-celadon/option.spec
  groups/boot-arch/project-celadon/product.mk
Labels: PR approved, Valid commit message

#1726 Use sw vulkan driver in VIRTIO-3D mode
  groups/graphics/auto/auto_hal.in
Labels: PR approved, Valid commit message

#1744 Clean up of License file since its no longer needed
  groups/device-specific/celadon_ivi/BoardConfig.mk
  groups/device-specific/celadon_ivi/product.mk
  groups/flashfiles/ini/flashfiles.ini
Labels: PR approved, Valid commit message

#1736 Create wlan1 interface for wifi ap mode on phy0 in init.rc
  groups/wlan/iwlwifi/init.rc
Labels: Invalid commit message, PR approved

#1686 Add perfetto trace tool to vendor image
  groups/graphics/auto/product.mk
Labels: PR approved, Valid commit message

#1750 Add sepolicy for intel defined property
  groups/graphics/auto/BoardConfig.mk
Labels: PR approved, Valid commit message

#1755 move iw from system bin to vendor bin
  groups/wlan/iwlwifi/init.rc
  groups/wlan/iwlwifi/product.mk
Labels: PR approved, Valid commit message

#1753 Add wifi ap/sta dual mode config in wlan/BoardConfig
  groups/wlan/iwlwifi/BoardConfig.mk
Labels: PR approved, Valid commit message
