Repository projectceladon/device-androidia-mixins, pull requests merged in 2023-11, with the labels that each got.

#1800 changing usb-gadget modules to static
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved, Valid commit message

#1807 Enable f2fs for data partition and add fsync_mode=nobarrier mount flag
  groups/boot-arch/project-celadon/fstab
  groups/boot-arch/project-celadon/option.spec
  groups/flashfiles/ini/flashfiles.ini
Labels: PR approved, Valid commit message

#1793 Camera-Add-aidl-camera-provider-for-external-camera
  groups/camera-ext/ext-camera-only/product.mk
  groups/device-specific/caas/framework_manifest.xml
  groups/device-specific/caas/manifest.xml
Labels: PR approved

#1808 Only add LCG_IMAGE_SOURCE for blizzard.
  groups/docker/true/AndroidBoard.mk
Labels: Valid commit message

#1758 Adding Android 12L related API changes
  groups/device-specific/celadon_ivi/celadon_ivi.mk
  groups/device-specific/celadon_ivi/manifest.xml
Labels: PR approved, Valid commit message

#1812 MIXIN changes for AIDL Conversion of Thermal HAL
  groups/device-specific/caas/framework_manifest.xml
  groups/device-specific/caas/manifest.xml
  groups/thermal/thermal-daemon/product.mk
Labels: PR approved, Valid commit message

#1813 Revert "linux-intel-lts2021: kernel config update due to rebase"
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved, Valid commit message

#1821 Change optee mixins to support ivshmem usage control
  groups/tee/optee/BoardConfig.mk
Labels: PR approved, Valid commit message

#1820 Support OTA from U disk
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
  groups/slot-ab/true/product.mk
  groups/storage/sdcard-mmc0-v-usb-sd-r/fstab
Labels: PR approved, Valid commit message

#1825 Modify flashfiles.ini to support android flash tool
  groups/flashfiles/ini/flashfiles.ini
Labels: PR approved, Valid commit message

#1818 System property to disable thermal logs
  groups/device-specific/celadon_ivi/system.prop
  groups/thermal/thermal-daemon/init.rc
Labels: PR approved, Valid commit message

#1840 Create new lunch target everest_ivi
  valid_targets.spec
Labels: PR approved, Valid commit message

#1842 serial spends about 260ms in kernel boot process
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: PR approved, Valid commit message

#1843 Change the path of ueventd.rc
  groups/device-specific/celadon_ivi/product.mk
Labels: PR approved, Valid commit message

#1835 Config country code CN in ro.boot.wificountrycode
  groups/wlan/iwlwifi/init.rc
Labels: PR approved, Valid commit message

#1815 blizzard use different prebuilt images
  groups/boot-arch/project-celadon/AndroidBoard.mk
Labels: PR approved, Valid commit message

#1839 Add CONFIG_DRM_I915_MEMTRACK kernel config
  groups/kernel/gmin64/config-lts/linux-intel-lts2021/x86_64_defconfig
Labels: Invalid commit message, PR approved

#1844 Put TEE SBL container to tee partition
  groups/boot-arch/project-celadon/AndroidBoard.mk
Labels: Valid commit message

#1847 Add support for 6.1 kernel with SRIOV support
  groups/kernel/AndroidBoard.mk
  groups/kernel/BoardConfig.mk
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/caas_diffconfig
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/debug_diffconfig
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
  groups/kernel/option.spec-gmin
Labels: PR approved
