Repository projectceladon/device-androidia-mixins, pull requests merged in 2023-03, with the labels that each got.

#1587 Enable sw rendering.
  groups/graphics/auto/auto_hal.in
  groups/graphics/auto/product.mk
Labels: PR approved

#1585 Mixin changes required for openvino 2022.3.0
  groups/neuralnetworks/true/plugins.xml
  groups/neuralnetworks/true/product.mk
Labels: PR approved, Valid commit message

#1594 Cleanup of Device/intel/common
  exempt_groups.txt
Labels: Valid commit message

#1595 Mixins group for device-specific caas_dev
  groups/device-specific/caas_dev/BoardConfig.mk
  groups/device-specific/caas_dev/addon/debian/control
  groups/device-specific/caas_dev/caas_dev.mk
  groups/device-specific/caas_dev/cam_sharing/0001-Netlink-sync.patch
  groups/device-specific/caas_dev/cam_sharing/IntelCameraService
  groups/device-specific/caas_dev/cam_sharing/virtualcamera.service
  groups/device-specific/caas_dev/compatibility_matrix.xml
  groups/device-specific/caas_dev/file_share.sh
  groups/device-specific/caas_dev/files.spec
  groups/device-specific/caas_dev/framework_manifest.xml
  groups/device-specific/caas_dev/guest_pm_control
  groups/device-specific/caas_dev/init.rc
  groups/device-specific/caas_dev/intel-thermal-conf.xml
  groups/device-specific/caas_dev/manifest.xml
  groups/device-specific/caas_dev/overlay/frameworks/base/core/res/res/values/config.xml
  groups/device-specific/caas_dev/overlay/frameworks/base/core/res/res/values/dimens.xml
  groups/device-specific/caas_dev/overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
  groups/device-specific/caas_dev/overlay/frameworks/base/packages/SystemUI/res/values/config.xml
  groups/device-specific/caas_dev/product.mk
  groups/device-specific/caas_dev/remote_infer/README.txt
  groups/device-specific/caas_dev/remote_infer/adaptors/base_adaptor.py
  groups/device-specific/caas_dev/remote_infer/adaptors/create_interface.py
  groups/device-specific/caas_dev/remote_infer/adaptors/ovms/interface.py
  groups/device-specific/caas_dev/remote_infer/adaptors/ovms/load_model.py
  groups/device-specific/caas_dev/remote_infer/adaptors/ovtoolkit/interface.py
  groups/device-specific/caas_dev/remote_infer/adaptors/ovtoolkit/load_model.py
  groups/device-specific/caas_dev/remote_infer/client_requirements.txt
  groups/device-specific/caas_dev/remote_infer/object_detection.sh
  groups/device-specific/caas_dev/remote_infer/services/rawTensor/nnhal_raw_tensor.proto
  groups/device-specific/caas_dev/remote_infer/services/rawTensor/rawTensor.py
  groups/device-specific/caas_dev/setup_audio_host.sh
  groups/device-specific/caas_dev/setup_rinfer_host.sh
  groups/device-specific/caas_dev/sof_audio/blacklist-dsp.conf
  groups/device-specific/caas_dev/sof_audio/configure_sof.sh
  groups/device-specific/caas_dev/wakeup.py
Labels: PR approved, Valid commit message

#1596 [PM] remove delay for host shutdown
  groups/device-specific/caas/guest_pm_control
  groups/device-specific/caas_dev/guest_pm_control
Labels: PR approved, Valid commit message

#1597 Disable Default enablement of Freeform mode
  groups/device-type/tablet/product.mk
Labels: Valid commit message
