Repository projectceladon/device-androidia-mixins, pull requests merged in 2024-06, with the labels that each got.

#1939 Fixed CTS issue testHasMsOsDescriptors
  groups/usb-gadget/auto/init.rc
Labels: PR approved, Valid commit message, Developer Approved

#1945 Fix regression caused by performance point
  groups/codec2/true/media_codecs_intel_c2_video.xml
Labels: PR approved, Valid commit message, Developer Approved

#1936 Support av1 8k decoding
  groups/codec2/true/media_codecs_intel_c2_video.xml
Labels: PR approved, Valid commit message, Developer Approved

#1947 Enable kernel config for crash memory dump
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/debug_diffconfig
Labels: PR approved, Valid commit message, Developer Approved

#1950 Add kernel config entry for Crash Memory Dump shmem driver
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
Labels: PR approved, Valid commit message, Developer Approved

#1952 Adopt aidl software gatekeeper hal implementation
  groups/tee/false/product.mk
  groups/tee/optee/product.mk
Labels: PR approved, Valid commit message

#1955 New Target aaos_iasw is created based out of base_aaos
  groups/device-specific/.gitignore
  valid_targets.spec
Labels: PR approved, Valid commit message, Developer Approved

#1956 New Target aaos_iasw is created
  groups/boot-arch/project-celadon/aaos_iasw/acpi/dummy.dtb
Labels: PR approved, Valid commit message, Developer Approved

#1959 Add docker into .gitignore.
  groups/.gitignore
Labels: Invalid commit message, PR approved, Valid commit message, Developer Approved
