Repository projectceladon/device-androidia-mixins, pull requests merged in 2024-08, with the labels that each got.

#1982 Load audio modules for BM case
  groups/audio/project-celadon/init.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1987 add separate xml for caas
  groups/codec2/true/files.spec
  groups/codec2/true/media_profiles_caas.xml
  groups/codec2/true/option.spec
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1806 Update manifest and package for composer3 AIDL HAL service
  groups/device-specific/caas/manifest.xml
  groups/device-specific/caas/product.mk
  groups/graphics/auto/BoardConfig.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1991 Enable loading vendor.intel.video.codec based on sysfs
  groups/media/auto/auto_hal.in
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1983 Optimize egl driver prop setting logic
  groups/graphics/auto/auto_hal.in
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1988 Update kernel config for v6.1.92 rebase
  groups/kernel/gmin64/config-lts/lts2022-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful

#1981 Updated Automotive Vehicle HAL.
  groups/device-type/car/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1995 Add sepolicy for application rendering setting property
  groups/graphics/auto/BoardConfig.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1971 Add Widevine L3 build targets
  groups/widevine/L3_Gen/BoardConfig.mk
  groups/widevine/L3_Gen/product.mk
  groups/widevine/default/BoardConfig.mk
  groups/widevine/default/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Not Started

#2014 Enable AV1 encoder in DG2
  groups/codec2/true/auto_hal.in
  groups/codec2/true/files.spec
  groups/codec2/true/media_codecs_gen13.xml
  groups/codec2/true/media_codecs_intel_c2_video_gen13.xml
  groups/codec2/true/mfx_c2_store_gen13.conf
  groups/codec2/true/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2006 Rename i965_drv_video to iHD_drv_video
  groups/media/auto/product.mk
  groups/media/mesa/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2009 Modify xml to pass MediaV2 EncoderProfileLevelTest
  groups/codec2/true/media_codecs_intel_c2_video.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#1974 remove vhal code building
  groups/camera-ext/ext-camera-only/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2012 Remove libpciaccess
  groups/media/auto/product.mk
  groups/media/mesa/product.mk
Labels: PR approved, Valid commit message, Engineering Build Successful

#1979 add intel evs hal binary
  groups/device-type/car/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2019 Evs intel app mixins
  groups/device-type/car/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2018 Use lz4 compression for EROFS filesystem
  groups/boot-arch/project-celadon/BoardConfig.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful
