Repository projectceladon/device-androidia-mixins, pull requests merged in 2025-03, with the labels that each got.

#2199 Enable i915 PXP for Widewine.
  groups/kernel/gmin64/config-lts/linux-intel-lts2023/x86_64_defconfig
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2284 Added secure codec configuration options
  groups/codec2/true/media_codecs_intel_c2_video.xml
  groups/codec2/true/mfx_c2_store.conf
  groups/codec2/true/option.spec
  groups/codec2/true/product.mk
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful

#2289 Revert "Bluetooth fix clearSignalStrengthUpdateRequest is unsupported…
  groups/bluetooth/btusb/android.hardware.telephony.automotive.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2287 Integrate attestation ids tool
  groups/tee/optee/init.rc
  groups/tee/optee/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2290 Add a display density config (200dpi)
  groups/display-density/200dpi/option.spec
  groups/display-density/200dpi/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2293 Support f2fs file system for metadata partition
  groups/boot-arch/project-celadon/fstab
  groups/boot-arch/project-celadon/fstab.recovery
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2296 Add prebuilt media close source driver
  groups/media/auto/product.mk
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful

#2295 mixins: disable thermal-daemon in AAOS VM
  groups/thermal/hal/BoardConfig.mk
  groups/thermal/hal/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2300 Fix testAlignmentSupport
  groups/codec2/true/media_codecs_intel_c2_video.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2277 enable usb audio
  groups/audio/audio_base_aaos/default/policy/car_audio_configuration.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2282 Add feature dynamic-color-aspects for decoders.
  groups/codec2/true/media_codecs_intel_c2_video.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2283 virtio/spi: add virtio spi controller support
  groups/kernel/gmin64/config-lts/lts2024-android/x86_64_defconfig
Labels: Valid commit message, Pending Developer Approval, Engineering Build Not Started, Pending PR Review

#2276 Fix to improve Android alarm context switch latency
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_attached_devices.xml
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_devices.xml
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_mixports.xml
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_routes.xml
  groups/audio/audio_base_aaos/default/policy/car_audio_configuration.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2258 Remove start hdcpd
  groups/graphics/auto/init.rc.1
  groups/hdcpd/true/init.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2307 Store the dgpu-renderwlocal.cfg to /vendor/etc/
  groups/graphics/auto/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2303 virtio snd change to ko
  groups/audio/audio_base_aaos/init.rc
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/aaos_diffconfig
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2260 Update kernel config for v5.15.170 rebase
  groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2309 mixin: correct thermal hal package name
  groups/thermal/hal/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2313 Define the system_ext sepolicy related dirs
  groups/sepolicy/BoardConfig.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2311 Update group for audio contexts
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_attached_devices.xml
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_devices.xml
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_mixports.xml
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_routes.xml
  groups/audio/audio_base_aaos/default/policy/car_audio_configuration.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2286 virtio/camera: add virtio camera support
  groups/kernel/gmin64/config-lts/lts2024-android/x86_64_defconfig
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2280 media: ipu7: add config for ipu7 driver
  groups/kernel/gmin64/config-lts/lts2024-android/x86_64_defconfig
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Not Started

#2305 Add L1_Gen for Widevine
  groups/widevine/L1_Gen/BoardConfig.mk
  groups/widevine/L1_Gen/option.spec
  groups/widevine/L1_Gen/product.mk
Labels: Invalid commit message, PR approved, Developer Approved, Engineering Build Successful

#2308 Add v4l2loopback driver for camera sharing
  groups/kernel/AndroidBoard.mk
  groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
  groups/v4l2loopback/default
  groups/v4l2loopback/doc.spec
  groups/v4l2loopback/false/empty_dir
  groups/v4l2loopback/true/init.rc
  groups/v4l2loopback/true/ueventd.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2316 Replace car_core_hardware.xml which will disable location service
  groups/device-type/car/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2310 Fix for CTS CtsVoiceInteractionTestCases
  groups/audio/audio_base_aaos/default/policy/audio_policy_configuration_mixports.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2319 Support 1600x1300 as quality high for video codec
  groups/codec2/true/media_profiles_1080p.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2321 Remove unused recovery modules
  groups/vendor-partition/true/AndroidBoard.mk
  groups/vendor-partition/true/files.spec
  groups/vendor-partition/true/sh_recovery
  groups/vendor-partition/true/toolbox_recovery
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2323 Remove unused recovery modules
  groups/vendor-partition/true/AndroidBoard.mk
  groups/vendor-partition/true/files.spec
  groups/vendor-partition/true/sh_recovery
  groups/vendor-partition/true/toolbox_recovery
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful
