Repository projectceladon/device-androidia-mixins, pull requests merged in 2025-01, with the labels that each got.

#2207 Add usbcore.uevent_suppress for Bluetooth
  groups/bluetooth/btusb/BoardConfig.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2213 Fixed for usb debugging configuration
  groups/kernel/gmin64/config-lts/lts2023-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2211 Fix for "Alarm tone plays on zone1 instead of zone0"
  groups/audio/audio_base_aaos/default/policy/car_audio_configuration.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2218 Fix Python warnings in mixins-update
  mixin-update
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2215 Re-Enable vendor AIDL Audio HAL
  groups/audio/audio_base_aaos/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Failed

#2214 Enable vsomeip support
  groups/vsomeip/default
  groups/vsomeip/doc.spec
  groups/vsomeip/false/empty_dir
  groups/vsomeip/true/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2220 update mixins for vhal
  groups/device-type/car/product.mk
  groups/device-type/car/ueventd.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2143 Changes to enable angle and vulkan as backend
  groups/graphics/auto/auto_hal.in
  groups/graphics/auto/init.rc
  groups/graphics/auto/option.spec
  groups/graphics/auto/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2219 Fix for STS effects test
  groups/audio/audio_base_aaos/default/effect/audio_effects_config.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2222 Trusty kernel config enablement
  groups/kernel/gmin64/config-lts/lts2023-chromium/caas_diffconfig
  groups/kernel/gmin64/config-lts/lts2023-chromium/x86_64_defconfig
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful

#2228 Adding new mixins group: rdtsc
  groups/rdtsc/default
  groups/rdtsc/doc.spec
  groups/rdtsc/false/empty_dir
  groups/rdtsc/true/BoardConfig.mk
  groups/rdtsc/true/init.rc
  groups/rdtsc/true/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2230 fix mixin-update SyntaxWarning: invalid escape sequence
  mixin-update
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2234 Make encoder support identical size ranges for width and height
  groups/codec2/true/media_codecs_intel_c2_video.xml
  groups/codec2/true/media_codecs_intel_c2_video_gen13.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2233 add kernel cmdline: usbcore.intel_btdev
  groups/bluetooth/auto/ueventd.rc
  groups/bluetooth/btusb/BoardConfig.mk
  groups/bluetooth/btusb/ueventd.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2236 linux-intel-lts2023: Update config for v6.6.68 rebase
  groups/kernel/gmin64/config-lts/linux-intel-lts2023/x86_64_defconfig
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2238 Add node creation for uvcvideo virtvideo
  groups/camera-ext/aaos_iasw/ueventd.rc
  groups/camera-ext/base_aaos/ueventd.rc
  groups/camera-ext/ext-camera-only/ueventd.rc
  groups/camera-ext/true/ueventd.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2240 Removed Clipboard Agent from Android 15
  groups/device-specific/caas/BoardConfig.mk
  groups/device-specific/caas/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2241 Fix for "no exclusive media control UI"
  groups/audio/audio_base_aaos/default/policy/car_audio_configuration.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2244 Add btusb dev path for celadon target
  groups/bluetooth/btusb/ueventd.rc
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2216 Changes to support android v6.12 kernel
  groups/device-specific/caas/caas.mk
  groups/kernel/AndroidBoard.mk
  groups/kernel/BoardConfig.mk
  groups/kernel/gmin64/config-lts/lts2024-android/aaos_diffconfig
  groups/kernel/gmin64/config-lts/lts2024-android/caas_diffconfig
  groups/kernel/gmin64/config-lts/lts2024-android/debug_diffconfig
  groups/kernel/gmin64/config-lts/lts2024-android/virt_diffconfig
  groups/kernel/gmin64/config-lts/lts2024-android/x86_64_defconfig
  groups/kernel/option.spec-gmin
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2239 Add build flag to chose between prebuilt mesa and build from source
  groups/device-specific/caas/BoardConfig.mk
  groups/graphics/auto/BoardConfig.mk
  groups/graphics/auto/option.spec
  groups/graphics/auto/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2247 kernel: Remove unused configs
  groups/kernel/BoardConfig-sofia-lte-lte2.mk
  groups/kernel/BoardConfig-sofia-lte.mk
  groups/kernel/BoardConfig-sofia-lte2.mk
  groups/kernel/BoardConfig-sofia.mk
  groups/kernel/coho64/AndroidBoard.mk
  groups/kernel/coho64/BoardConfig.mk
  groups/kernel/coho64/option.spec
  groups/kernel/coho64/product.mk
  groups/kernel/coho64/product.mk.1
  groups/kernel/sflte2_32/AndroidBoard.mk
  groups/kernel/sflte2_32/BoardConfig.mk
  groups/kernel/sflte2_32/BoardConfig.mk.1
  groups/kernel/sflte2_32/BoardConfig.mk.2
  groups/kernel/sflte2_32/init.rc
  groups/kernel/sflte2_32/option.spec
  groups/kernel/sflte2_32/product.mk
  groups/kernel/sflte2_32/product.mk.1
  groups/kernel/sofia3g32/AndroidBoard.mk
  groups/kernel/sofia3g32/BoardConfig.mk
  groups/kernel/sofia3g32/BoardConfig.mk.1
  groups/kernel/sofia3g32/init.rc
  groups/kernel/sofia3g32/option.spec
  groups/kernel/sofia3g32/product.mk
  groups/kernel/sofia3g32/product.mk.1
  groups/kernel/sofia3g64/AndroidBoard.mk
  groups/kernel/sofia3g64/BoardConfig.mk
  groups/kernel/sofia3g64/BoardConfig.mk.1
  groups/kernel/sofia3g64/BoardConfig.mk.2
  groups/kernel/sofia3g64/init.rc
  groups/kernel/sofia3g64/option.spec
  groups/kernel/sofia3g64/product.mk
  groups/kernel/sofia3g64/product.mk.1
  groups/kernel/sofialte32/AndroidBoard.mk
  groups/kernel/sofialte32/BoardConfig.mk
  groups/kernel/sofialte32/BoardConfig.mk.1
  groups/kernel/sofialte32/BoardConfig.mk.2
  groups/kernel/sofialte32/init.rc
  groups/kernel/sofialte32/option.spec
  groups/kernel/sofialte32/product.mk
  groups/kernel/sofialte32/product.mk.1
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#2245 CTS fix for BatteryHealth module
  groups/health/hal/product.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful
